### PR TITLE
JavaFX work

### PR DESCRIPTION
**Pull request by fstonedahl**
I think we're ready to roll with An's JavaFX update now.  

The key changes for distribution that still needs to happen:

- [x] The BehaviorSearch GUI launcher should be changed to launch **bsearch.fx.MainGUI** instead of **bsearch.app.BehaviorSearchGUI.java**.  The headless stuff remains unchanged...
- [x] Test whether the JavaFX version works on Mac (I don't see why it wouldn't, but I don't have a Mac to test...)

### CODE REVIEW

**Comment by fstonedahl** [comment]
Update: I also realized that MainGUI (JavaFX) is launching fine from Eclipse (after I added all the appropriate libraries to my build path), but it *not* launching fine with **sbt run**.  I fixed one problem by including a reference to jfxrt.jar inside build.sbt.

However, there seem to be at least two remaining problems:

1. It's not copying the .fxml files from inside bsearch.fx into the target/classes/bsearch/fx folder, where JavaFX tries to look for them.  (I manually copied them there, and then it would launch)
2. It seems to all run okay, but it hangs (with an InterruptedException) when I try to close the main BehaviorSearch window.

**Comment by mrerrormessage** [comment]
I was able to fix problems 1 and 2 with [this commit](https://github.com/NetLogo/behaviorsearch/commit/da6453fda3ebee118eec2d79f4662b3d7fdf6eb9). Most java project store source files in one directory (often src/main/java) and resource files in another (typically src/main/resources). I was able to tell sbt to do it the way you have it setup here, but it might be worth considering whether that's a more effective project layout going forward. I didn't make that change initially because I wanted to keep the changeset as small as possible.

I notice from the PR that there are a bunch of changes due to files being saved with different line endings. I think the best way to deal with this would be to add a [gitattributes file](https://help.github.com/articles/dealing-with-line-endings/). Would you prefer code files in this project have CR or CRLF endings? I will gladly add a gitattributes file once I know your preference.

**Comment by fstonedahl** [comment]
I thought I squelched all the line endings changes, but perhaps not... in general, I would prefer all the source code to use CR ("\n").  However, maybe the .BAT file for launching headless windows needs to have CRLF in order to run?

**Comment by mrerrormessage** [comment]
Oh, I didn't read the commit history and didn't notice that line-endings were actually part of this pull request. I've added a gitattributes file and restored the crlf endings to the bat script in [this commit](https://github.com/NetLogo/behaviorsearch/commit/e5ab82e6257c0fcf57640cce111507e568e19bbc). I can either (a) merge this PR and apply my commits on top, or (b) open a PR for my changes into your branch and merge this PR after those changes have been merged. Let me know what you prefer.

**Comment by fstonedahl** [comment]
Go ahead with option a), and then I can pull your changes back.  (Right now I'm doing all my new work in fstonedahl on the multiobj topic branch, but that won't be ready to merge in to master for quite a while.)

**Comment by mrerrormessage** [comment]
This has now been merged into master. I needed one additional change to get it working ([here](https://github.com/NetLogo/behaviorsearch/commit/7258d6666bf049c216d8da6b00126f633061ac6c)) - configuring a JavaFX file chooser to open in "save" mode instead of "open" mode since we are, in the case of a new run, looking to save a group of files in a location that doesn't (or may not) exist yet.

I'll be updating NetLogo to include this version shortly, now that I've tested it on Mac and Windows. It should be included in the 6.0.2 release.

**Comment by fstonedahl** [comment]
Excellent - thanks!

**Pull request merged**
